config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#welcome'

  resources :kameras

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kamera.rb
class Kamera < ApplicationRecord
    include ActionView::Helpers::TextHelper
    belongs_to :user
    has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ""
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :kameras
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kameras_controller.rb
class KamerasController < ApplicationController
  before_action :authenticate_user!
  before_action :is_owner?, only: [:edit, :update, :destroy]

  def index
    @kameras = Kamera.all
    @user = current_user
  end

  def new
    @kamera = Kamera.new  
  end

  def create
    @kamera = Kamera.new(kamera_params)
    @kamera.user_id = current_user
    current_user.kameras << @kamera
    if @kamera.save
      flash[:success] = 'Kamera tika pievienota veiksmīgi!'
      redirect_to root_path 
    else  
      flash[:danger] = @kamera.errors.full_messages
      render 'new'
    end
  end


  def edit
    @kamera = Kamera.find(params[:id])
  end

  def update
    @kamera = Kamera.find(params[:id])
    @kamera.update(kamera_params)
    if @kamera.save
      flash[:success] = 'Kameras dati tika veiksmīgi atjaunināti!'
      redirect_to kameras_path
    else
      flash[:danger] = @kamera.errors.full_messages
      redirect_to kameras_path
    end
  end

  def destroy 
    @kamera = Kamera.find(params[:id])
    @kamera.destroy
    redirect_to kameras_path
  end

  private

  def kamera_params
    params.require(:kamera).permit(:user_id, :modelis, :razotajs, 
    :serijasnr, :valsts, :eksempsk, :cena, :papildinformacija, :vertejums, :photo)
  end

  def is_owner?
    @kamera = Kamera.find(params[:id])
    if current_user.id == @kamera.user_id
      return
    else
      flash[:danger] = "You are not authorized to perform this action!"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kameras_helper.rb
module KamerasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/kameras/edit.html.erb
<h2>Kameras datu labošana/atjaunināšana</h2>
<hr></hr>

<%= form_for @kamera, html: { multipart: true } do |f| %>
  <div class="form-group">
    <div class="control-label">
      <%= f.label "Modelis" %>
    </div>
    <div class="">
      <%= f.text_field :modelis %>
    </div>

    <div class="control-label">
      <%= f.label "Ražotājs" %>
    </div>
    <div class="">
      <%= f.text_field :razotajs %>
    </div>
    
    <div class="control-label">
      <%= f.label "Sērijas Numurs" %>
    </div>
    <div class="">
      <%= f.text_field :serijasnr %>
    </div>

    <div class="control-label">
      <%= f.label "valsts" %>
    </div>
    <div class="">
      <%= f.text_field :valsts %>
    </div>

    <div class="control-label">
      <%= f.label "Eksemplāru skaits" %>
    </div>
    <div class="">
      <%= f.text_field :eksempsk %>
    </div>

    <div class="control-label">
      <%= f.label "Cena" %>
    </div>
    <div class="">
      <%= f.text_field :cena %>
    </div>

    <div class="control-label">
      <%= f.label "Papildinformācija" %>
    </div>
    <div class="">
      <%= f.text_field :papildinformacija, class: 'form-control', placeholder: '....', autofocus: true %>
    </div>

    <div class="control-label">
        <%= f.label "Vērtējums" %>
    </div>
    <div class="control-label">
        <%= f.text_field :vertejums %>
    </div>

    <div class="control-label">
        <%= f.label "Foto" %>
    </div>
    <div class="control-label">
        <%= f.file_field :photo %>
    </div>

    <div class="">
      </br>
      <%= f.submit "Labot", class: 'btn btn-primary btn-lg' %>
    </div>
  </div>

<% end %>

app/views/kameras/index.html.erb
<h1 align="center">Kameru saraksts</h1>
<hr>

<div>
    <div class="row">
        <div class="col-md-1"><small style="font-weight:bold">Foto</small></div>
        <div class="col-md-2"><small style="font-weight:bold">Modelis</small></div>
        <div class="col-md-2"><small style="font-weight:bold">Ražotājs</small></div>
        <div class="col-md-1"><small style="font-weight:bold">Sērijas Nr.</small></div>
        <div class="col-md-1"><small style="font-weight:bold">Valsts</small></div>
        <div class="col-md-1"><small style="font-weight:bold">Eksemplāri</small></div>
        <div class="col-md-1"><small style="font-weight:bold">Cena</small></div>
        <div class="col-md-2"><small style="font-weight:bold">Papildinformācija</small></div>
        <div class="col-md-1"><small style="font-weight:bold">Vērtējums</small></div>
    </div>
</div>

<br>



<% @user.kameras.each do |x| %>
    <div class="well">
        <div class="row">
           <div class="col-md-1 smlpad lolclass">
                <%= image_tag x.photo.url(:thumb) %>
                <%= link_to edit_kamera_path(x.id) do %>
                    <%= image_tag  "edit-icon.png", width: 25, height: 25 %>
                <% end %>
                <%= link_to kamera_path(x.id), method: :delete, data: {confirm: "Vai tiešām vēlaties šo ierakstu dzēst?"} do %>
                    <%= image_tag  "delete-icon.png", width: 25, height: 25 %>
                <% end %>
           </div> 
           <div class="col-md-2 smlpad">
                <small><%= x.modelis.truncate(25) %></small>  
           </div>
           <div class="col-md-2 smlpad">
                <small><%= x.razotajs.truncate(25) %></small> 
           </div>
           <div class="col-md-1 smlpad">
                <small><%= x.serijasnr %></small>  
           </div>
           <div class="col-md-1 smlpad">
                <small><%= x.valsts.truncate(13) %></small>  
           </div>
           <div class="col-md-1 smlpad">
                <small><%= x.eksempsk %></small>  
           </div>
           <div class="col-md-1 smlpad">
                <small><%= x.cena %></small>  
           </div>
           <div class="col-md-2 smlpad">
                <small><%= x.papildinformacija.truncate(25) %></small> 
           </div>
           <div class="col-md-1 smlpad">
                <small><%= x.vertejums %></small>   
           </div>
        </div>
    </div>
    <hr>
<% end %>

app/views/kameras/kolekcija.html.erb
<h1>Kameras#kolekcija</h1>
<p>Find me in app/views/kameras/kolekcija.html.erb</p>

app/views/kameras/kopsavilkums.html.erb
<h1>Kameras#kopsavilkums</h1>
<p>Find me in app/views/kameras/kopsavilkums.html.erb</p>

app/views/kameras/new.html.erb
<h2>Jaunas kameras ievade</h2>
<hr></hr>

<%= form_for @kamera do |f| %>
  <div class="form-group">
    <div class="control-label">
      <%= f.label "Modelis" %>
    </div>
    <div class="">
      <%= f.text_field :modelis %>
    </div>

    <div class="control-label">
      <%= f.label "Ražotājs" %>
    </div>
    <div class="">
      <%= f.text_field :razotajs %>
    </div>
    
    <div class="control-label">
      <%= f.label "Sērijas Numurs" %>
    </div>
    <div class="">
      <%= f.text_field :serijasnr %>
    </div>

    <div class="control-label">
      <%= f.label "valsts" %>
    </div>
    <div class="">
      <%= f.text_field :valsts %>
    </div>

    <div class="control-label">
      <%= f.label "Eksemplāru skaits" %>
    </div>
    <div class="">
      <%= f.text_field :eksempsk %>
    </div>

    <div class="control-label">
      <%= f.label "Cena" %>
    </div>
    <div class="">
      <%= f.text_field :cena %>
    </div>

    <div class="control-label">
      <%= f.label "Papildinformācija" %>
    </div>
    <div class="">
      <%= f.text_field :papildinformacija, class: 'form-control', placeholder: '....', autofocus: true %>
    </div>

    <div class="control-label">
        <%= f.label "Vērtējums" %>
    </div>
    <div class="">
        <%= f.text_field :vertejums %>
    </div>

    <div class="">
      </br>
      <%= f.submit "Pievienot", class: 'btn btn-primary btn-lg' %>
    </div>
  </div>

<% end %>

app/views/kameras/pievienot.html.erb
<h1>Kameras#pievienot</h1>
<p>Find me in app/views/kameras/pievienot.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotocollector</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <%= link_to  "Sākums", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <% if !user_signed_in? %>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <%= link_to  "Ielogoties", new_user_session_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
          <% end %>
          <% if user_signed_in? %>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <%= link_to  "Kolekcija", kameras_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to  "Pievienošana", new_kamera_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Kopsavilkums</a>
                </li>
                <li class="nav-item">
                    <%= link_to  "Iziet", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Meklēt" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Aiziet!</button>
              </form>
            </div>
          <% end %>
        </nav>
        <% flash.each do |key, value| %>
          <%= content_tag :div, value, class: "flash #{key}" %>
        <% end %>
        
        <main role="main" class="container main-content">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                  <% flash.each do |name, msg| %>
                    <div class='"alert alert-<%="#{name}" %>'>
                      <a href="#" class="close" data-dismiss="alert"></a>
                      <%= content_tag :div, msg, :id => "flash_#{name}", align: 'center' if msg.is_a?(String) %>
                    </div>
                  <% end %>
                </div>
        </div>
            <%= yield %>
        </main>
    


  </body>
</html>

app/views/pages/welcome.html.erb
<%if user_signed_in? %>
    <h1>Sveiks, <%= current_user.email %></h1>
<% else %>
    <h1>Lai izmantotu šo lietotni, nepieciešams ielogoties!</h1>
<% end %>